path and CI update

diff --git a/.github/workflows/nested_eagle.yml b/.github/workflows/nested_eagle.yml
--- a/.github/workflows/nested_eagle.yml
+++ b/.github/workflows/nested_eagle.yml
@@ -106,7 +106,7 @@ jobs:
                sleep 30  # Wait for 30 seconds before checking again.
             done
 
-             echo "Slurm job $JOB_ID to run inference on the data has been completed."
+          echo "Slurm job $JOB_ID to run inference on the data has been completed."
 
   Perform_Inference_Postprocessing:
     # The type of runner that the job will run on
@@ -119,6 +119,7 @@ jobs:
           cd nested_eagle/ursa/scientific_workflow/verification/prewxvx
 
           mkdir -p postprocessed_files/lam
+          mkdir -p postprocessed_files/global
 
           JOB_ID=$(sbatch submit_postprocessing.sh | awk '{print $4}')
 
@@ -128,8 +129,11 @@ jobs:
                squeue -j $JOB_ID
                sleep 30  # Wait for 30 seconds before checking again.
             done
-             
-             echo "Slurm job $JOB_ID to perform inference postprocessing has been completed."
+
+          cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/prewxvx/postprocessed_files
+          find ./nested-global -name "*.nc" -print -quit | grep -q . || { echo "Error: No global postprocessed files found."; exit 1; } 
+          find ./nested-lam -name "*.nc" -print -quit | grep -q . || { echo "Error: No lam postprocessed files found."; exit 1; } 
+          echo "Slurm job $JOB_ID to perform inference postprocessing has been completed."
 
   Perform_Verification:
     # The type of runner that the job will run on
